name: CI

on:
  push:
    branches: [ dev01 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: |
        sudo apt-get update 
        sudo apt-get install -y g++ cmake
    - name: install googletest
      run: |
        sudo apt-get install libgtest-dev -y
        sudo cp -r /usr/src/gtest /usr/src/mygtest
        cd /usr/src/mygtest
        sudo cmake .
        sudo make
        sudo cp ./lib/*.a /usr/lib
    - name: run build.sh
      run: chmod +x ./build.sh && ./build.sh
