name: CI

on:
  push:
    branches: [ main ] # ワークフローを実行するブランチを指定
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest # ワークフローの実行環境を指定
    container: 
      image: gentoo/stage3-amd64

    steps:
    - uses: actions/checkout@v2 # リポジトリのソースコードをチェックアウト

    - name: Setup dependencies
      run: |
        emerge --sync
        emerge dev-util/lcov # 必要な依存をインストール

    - name: Run Tests
      run: make test # あなたのテストコマンドに適宜置き換えてください

    - name: Generate Coverage
      run: |
        lcov --directory . --capture --output-file coverage.info
        lcov --remove coverage.info '/usr/*' --output-file coverage.info # 依存ライブラリを除外

    # カバレッジレポートのアップロードのためのステップも追加できます(オプショナル)

