name: CI

on:
  push:
    branches: [ dev01 ]

jobs:
  build:
    runs-on: ubuntu-latest
    needs: setup

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Test
      run: docker build -t my-app .
    
    - name: Generate Coverage
      run: docker run --rm -v ${{ github.workspace }}/coverage_report:/app/coverage_report my-app ./build.sh

    # カバレッジレポートのアップロードのためのステップも追加できます(オプショナル)
